REM Generate the executables
pyinstaller --onefile --upx-dir ./ ../build.py
pyinstaller --onefile --upx-dir ./ ../explode.py

REM Clean up all the files generated by the build process
del /f "build.spec"
del /f "explode.spec"
rmdir /q/s "build"
rmdir /q/s "../__pycache__"