REM Generate the executables
pyinstaller --onefile --noupx ../sprite_sheet_rebuilder.py

REM Clean up all the files generated by the build process
del /f "sprite_sheet_rebuilder.spec"
rmdir /q/s "build"
rmdir /q/s "../__pycache__"